version: '2'

services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER={{ postgres_user }}
      - POSTGRES_PASSWORD={{ postgres_password }}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  drone:
    image: drone/drone:1.0.0-rc.5
    depends_on:
      - postgres
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/drone:/data
    environment:
    - POSTGRES_USER={{ postgres_user }}
    - POSTGRES_PASSWORD={{ postgres_password }}
    - DRONE_GIT_ALWAYS_AUTH=false
    - DRONE_GITLAB_SERVER=https://gitlab.com
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_TLS_AUTOCERT=false
    - DRONE_SERVER_PROTO=https
    - DRONE_GITLAB_CLIENT_ID={{ drone_gitlab_client_id }}
    - DRONE_GITLAB_CLIENT_SECRET={{ drone_gitlab_client_secret }}
    - DRONE_GITHUB_SERVER=https://github.com
    - DRONE_GITHUB_CLIENT_ID={{ drone_github_client_id }}
    - DRONE_GITHUB_CLIENT_SECRET={{ drone_github_client_secret }}
    - DRONE_SERVER_HOST={{ server_domain }}
    - DRONE_DATABASE_DRIVER=postgres
    - DRONE_DATABASE_DATASOURCE=postgres://{{ postgres_user }}:{{ postgres_password }}@postgres:5432/postgres?sslmode=disable
    env_file:
     - .env
    restart: always
    links:
     - postgres
    ports:
      - 127.0.0.1:{{ server_port }}:80
